---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: upala-corporation/cp-kafka-oauth:5.3.1
    build: ./cp-kafka-oauth
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
      - 9093:9093
    environment:
      #BASE CONFLUENT ENVIRONMENTS
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      #KAFKA SASL SET HANDLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,SASL_PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092,SASL_PLAINTEXT://broker:9093
      KAFKA_LISTENER_NAME_SASL__PLAINTEXT_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: com.adobe.ids.dim.security.java.IMSAuthenticateValidatorCallbackHandler
      KAFKA_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      #KAKFA JAAS CONFIGURATION FILE
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf -javaagent:/usr/share/java/kafka/jolokia-jvm-1.6.2-agent.jar=port=49998,host=0.0.0.0"
      ZOOKEEPER_SASL_ENABLED: "FALSE"
      #KAFKA INTERBROKER SECURITY
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LOG4J_LOGGERS: "kafka.controller=DEBUG,org.apache.kafka=DEBUG"
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG

  schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

  rest-proxy:
    image: upala-corporation/cp-kafka-rest:5.3.1
    build: ./rest-proxy/
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'SASL_PLAINTEXT://broker:9093'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      KAFKA_REST_KAFKA_REST_RESOURCE_EXTENSION_CLASS: 'com.adobe.ids.dim.security.rest.KafkaOAuthSecurityRestResourceExtension'
      KAFKA_REST_CLIENT_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_REST_CLIENT_SASL_MECHANISM: OAUTHBEARER
      KAFKA_REST_CLIENT_SASL_LOGIN_CALLBACK_HANDLER_CLASS: com.adobe.ids.dim.security.java.IMSAuthenticateLoginCallbackHandler
      KAFKA_REST_IMS_REST_CLIENT_SASL_LOGIN_CALLBACK_HANDLER_CLASS: 'com.adobe.ids.dim.security.rest.IMSAuthenticateRestCallbackHandler'
      KAFKAREST_OPTS: '-Djava.security.auth.login.config=/etc/kafka-rest/kafka_rest_proxy_jaas.conf -javaagent:/usr/share/java/kafka-rest/jolokia-jvm-1.6.2-agent.jar=port=49998,host=0.0.0.0'
      #Only need for confluentinc/kafka-rest container
      CUB_CLASSPATH: "/etc/confluent/docker/docker-utils.jar:/usr/share/java/kafka-rest/kafka-sasl-oauth-handler-1.0-SNAPSHOT-jar-with-dependencies.jar -Djava.security.auth.login.config=/etc/kafka-rest/kafka_rest_proxy_jaas.conf"
      ################################################
      KAFKA_REST_LOG4J_LOGGERS: "kafka.controller=INFO,org.apache.kafka=INFO"
      KAFKA_REST_LOG4J_ROOT_LOGLEVEL: INFO
      
  hawtio-jmx:
    image: upala-corporation/hawtio-jmx
    build: ./hawtio-jmx/
    ports: 
        - 8080:8080

      



