FROM confluentinc/cp-kafka-rest:5.3.1

ADD config/kafka* /etc/kafka-rest/
ADD libs/kafka* /usr/share/java/
ADD libs/kafka* /usr/share/java/kafka-rest/
ADD libs/kafka* /usr/share/java/kafka/
ADD libs/kafka* /usr/share/java/confluent-common/
ADD libs/kafka* /usr/share/java/rest-utils/
ADD libs/kafka* /usr/lib/jvm/zulu-8-amd64/jre/lib/
ADD libs/kafka* /usr/share/java/confluent-security/schema-registry/
ADD libs/kafka* /usr/share/java/confluent-security/kafka-rest/
ADD libs/kafka* /etc/confluent/docker/